// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int overCounter = 0;
		int underCounter = 0;
		int numOfTimes =Integer.parseInt(args[0]);
		for(int i=0;i<numOfTimes; i++)	{
			double randCheck = Math.random();
			if (Math.random() > 0.5){
				overCounter++;
			}
			else {
				underCounter++;
			}
		}
		System.out.println("> 0.5:  " + overCounter + " times");
		System.out.println("<= 0.5: " + underCounter + " times");
		if (overCounter!=0 && underCounter!=0){
			double ratio = (double) overCounter/ (double) underCounter;
			System.out.println("Ratio:  " + ratio);
		}
	}
}
